name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "develop"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          path: /storybook-static
          build_command: npm run build-storybook
